[[redirects]]
  from = "/api/bookings"
  to = "/.netlify/functions/bookings"
  status = 200

[[redirects]]
  from = "/api/booking/:id"
  to = "/.netlify/functions/booking/:id"
  status = 200

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/services"
  to = "/.netlify/functions/services"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[redirects]]
  from = "/api/create-stripe-link"
  to = "/.netlify/functions/create-stripe-link"
  status = 200

[[redirects]]
  from = "/api/staff"
  to = "/.netlify/functions/staff"
  status = 200

[[redirects]]
  from = "/api/staff/:id"
  to = "/.netlify/functions/staff/:id"
  status = 200

[[redirects]]
  from = "/api/staff-assignments"
  to = "/.netlify/functions/staff-assignments"
  status = 200

[functions]
  node_bundler = "esbuild"
