[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/bookings"
  to = "/.netlify/functions/bookings"
  status = 200

[[redirects]]
  from = "/api/booking/:id"
  to = "/.netlify/functions/booking/:id"
  status = 200
